 server: 
   port: 8761
   
 eureka: 
  instance: 
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaulZone: http://${eureka.instance.hostname}:${server.port}/eureka/